### ISSUE TITLE
Please consider renaming this to something less generic than `zsh-theme`

### ISSUE THREAD

**Issue by unixorn** [abhiyandhakal/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name `zsh-theme` is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by abhiyandhakal** [comment]
Thank you for considering adding this theme to awesome-zsh-plugins. I couldn't come up with a descriptive name, so I think I will rename this repo to `abhiyan.zsh`. Please give me your feedback on the name.

**Comment by unixorn** [comment]
Sure, that's fine. Close this after you rename the repo and I'll get your theme into the next update

**Comment by abhiyandhakal** [comment]
I've now renamed it
